'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Language = 'id' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Comprehensive translations - Indonesian and English only
const translations: Record<Language, Record<string, string>> = {
  id: {
    // Navigation
    'nav.beranda': 'Beranda',
    'nav.profilDesa': 'Profil Desa',
    'nav.kampungTahu': 'Kampung Tahu',
    'nav.umkm': 'UMKM',
    'nav.project': 'Project',
    'nav.profilKkn': 'Profil KKN',
    // Hero
    'hero.title': 'Desa Babalan Lor',
    'hero.subtitle': 'Sebuah desa yang penuh dengan potensi hasil produksi lokal',
    'hero.explore': 'Jelajahi Desa',
    'hero.learnMore': 'Pelajari Lebih Lanjut',
    // About Section
    'about.title': 'Tentang Desa Babalan Lor',
    'about.desc1': 'Desa Babalan Lor adalah sebuah desa yang terletak di wilayah yang kaya akan keindahan alam dan budaya lokal. Desa ini dikenal dengan masyarakatnya yang ramah dan gotong royong yang masih sangat kental.',
    'about.desc2': 'Dengan pemandangan yang menawan dan udara yang sejuk, Desa Babalan Lor menawarkan pengalaman hidup yang harmonis antara manusia dan alam. Masyarakat desa senantiasa menjaga kelestarian lingkungan sambil mengembangkan potensi lokal untuk kesejahteraan bersama.',
    'about.quote': 'Bersama membangun desa yang sejahtera dan berkelanjutan',
    // Filosofi
    'filosofi.title': 'Filosofi Desa',
    'filosofi.quote': 'Mewujudkan desa yang mandiri, berbudaya, dan sejahtera dengan menjunjung tinggi nilai-nilai kearifan lokal.',
    'filosofi.desc': 'Filosofi Desa Babalan Lor mengedepankan prinsip kemandirian, pelestarian budaya, dan kesejahteraan masyarakat. Kami percaya bahwa dengan menjaga dan mengembangkan kearifan lokal yang telah diwariskan turun-temurun, desa dapat tumbuh menjadi komunitas yang kuat, harmonis, dan berkelanjutan.',
    // Stats
    'stats.title': 'Data Desa',
    'stats.subtitle': 'Statistik dan informasi umum tentang Desa Babalan Lor',
    'stats.penduduk': 'Penduduk',
    'stats.rw': 'RW',
    'stats.rt': 'RT',
    'stats.keluarga': 'Keluarga',
    // Features
    'features.title': 'Keunggulan Desa',
    'features.subtitle': 'Hal-hal yang membuat Desa Babalan Lor istimewa',
    'features.alam': 'Keindahan Alam',
    'features.alamDesc': 'Desa dengan pemandangan yang menawan dan udara yang sejuk, dikelilingi oleh sawah yang hijau.',
    'features.budaya': 'Budaya Lokal',
    'features.budayaDesc': 'Kearifan lokal yang masih terjaga dengan baik, termasuk tradisi dan adat istiadat yang diwariskan turun temurun.',
    'features.gotong': 'Gotong Royong',
    'features.gotongDesc': 'Semangat gotong royong yang masih sangat kental dalam kehidupan bermasyarakat sehari-hari.',
    'features.ekonomi': 'Potensi Ekonomi',
    'features.ekonomiDesc': 'Berbagai potensi ekonomi lokal yang terus dikembangkan untuk meningkatkan kesejahteraan masyarakat.',
    // Map
    'map.title': 'Lokasi Desa',
    'map.subtitle': 'Temukan lokasi Desa Babalan Lor di peta',
    'map.address': 'Alamat:',
    'map.addressValue': 'Desa Babalan Lor, Kecamatan Bojong, Kabupaten Pekalongan, Jawa Tengah',
    'map.directions': 'Dapatkan Petunjuk Arah',
    // Footer
    'footer.mission': 'Mewujudkan desa yang mandiri, berbudaya, dan sejahtera dengan menjunjung tinggi nilai-nilai kearifan lokal.',
    'footer.quickLinks': 'Tautan Cepat',
    'footer.contact': 'Hubungi Kami',
    'footer.copyright': '© 2026 Pemerintah Desa Babalan Lor. All rights reserved.',
    // Profil Desa Page
    'profilDesa.hero': 'Profil Desa',
    'profilDesa.heroSub': 'Informasi lengkap tentang Desa Babalan Lor',
    'profilDesa.lokasi': 'Lokasi Geografis',
    'profilDesa.koordinat': 'Koordinat Geografis',
    'profilDesa.kecamatan': 'Kecamatan:',
    'profilDesa.kabupaten': 'Kabupaten:',
    'profilDesa.ketinggian': 'Ketinggian:',
    'profilDesa.ketinggianValue': '± 50 meter di atas permukaan laut',
    'profilDesa.batas': 'Batas Wilayah',
    'profilDesa.utara': 'Sebelah Utara:',
    'profilDesa.selatan': 'Sebelah Selatan:',
    'profilDesa.timur': 'Sebelah Timur:',
    'profilDesa.barat': 'Sebelah Barat:',
    'profilDesa.data': 'Data Geografis',
    'profilDesa.jumlahPenduduk': 'Jumlah Penduduk',
    'profilDesa.jumlahKeluarga': 'Jumlah Keluarga',
    'profilDesa.luasWilayah': 'Luas Wilayah',
    'profilDesa.struktur': 'Struktur Pemerintahan Desa',
    'profilDesa.usaha': 'Usaha Lokal',
    'profilDesa.jeanConvection': 'Jean Convection',
    'profilDesa.industri': 'Industri Konveksi Jeans',
    'profilDesa.industriDesc1': 'Desa Babalan Lor dikenal sebagai pusat industri konveksi jeans yang berkembang pesat. Usaha konveksi jeans telah menjadi tulang punggung perekonomian masyarakat desa, menyerap banyak tenaga kerja lokal dan memberikan kontribusi signifikan terhadap kesejahteraan masyarakat.',
    'profilDesa.industriDesc2': 'Produk jeans yang dihasilkan oleh pengusaha lokal di Desa Babalan Lor telah dikenal kualitasnya dan dipasarkan ke berbagai daerah. Industri ini tidak hanya memberikan lapangan pekerjaan, tetapi juga menjadi identitas ekonomi desa yang membanggakan.',
    'profilDesa.unitUsaha': 'Unit Usaha',
    'profilDesa.tenagaKerja': 'Tenaga Kerja',
    'profilDesa.lihatUMKM': 'Lihat Detail UMKM',
    // Kampung Tahu Page
    'kampungTahu.hero': 'Kampung Tahu',
    'kampungTahu.heroSub': 'Wisata Edukasi Inovatif di Desa Babalan Lor',
    'kampungTahu.about': 'Tentang Kampung Tahu',
    'kampungTahu.aboutDesc1': 'Kampung Tahu di Desa Babalan Lor merupakan destinasi wisata edukasi yang unik, menawarkan pengalaman langsung dalam proses pembuatan tahu tradisional. Wisatawan dapat belajar tentang kearifan lokal dan proses produksi tahu yang telah menjadi bagian dari kehidupan masyarakat desa.',
    'kampungTahu.aboutDesc2': 'Melalui kolaborasi dengan berbagai pihak, Kampung Tahu terus dikembangkan sebagai pusat wisata edukasi yang inovatif, menggabungkan tradisi lokal dengan konsep wisata modern untuk meningkatkan kesejahteraan masyarakat.',
    'kampungTahu.wisata': 'Wisata Edukasi',
    'kampungTahu.wisataDesc': 'Pelajari proses pembuatan tahu tradisional langsung dari para pengrajin berpengalaman',
    'kampungTahu.kearifan': 'Kearifan Lokal',
    'kampungTahu.kearifanDesc': 'Rasakan kearifan lokal yang masih terjaga dan menjadi bagian dari kehidupan sehari-hari',
    'kampungTahu.ekonomi': 'Ekonomi Lokal',
    'kampungTahu.ekonomiDesc': 'Dukung perekonomian lokal dengan membeli produk tahu langsung dari pengrajin',
    'kampungTahu.proses': 'Proses Pembuatan Tahu',
    'kampungTahu.persiapan': 'Persiapan',
    'kampungTahu.persiapanDesc': 'Siapkan bahan baku kedelai berkualitas',
    'kampungTahu.pengolahan': 'Pengolahan',
    'kampungTahu.pengolahanDesc': 'Proses perendaman dan penggilingan',
    'kampungTahu.pembentukan': 'Pembentukan',
    'kampungTahu.pembentukanDesc': 'Pembentukan tahu dengan cetakan tradisional',
    'kampungTahu.pemasakan': 'Pemasakan',
    'kampungTahu.pemasakanDesc': 'Proses pemasakan dan pengemasan',
    // UMKM Page
    'umkm.hero': 'UMKM',
    'umkm.heroSub': 'Usaha Mikro Kecil Menengah Desa Babalan Lor',
    'umkm.about': 'Tentang UMKM Desa Babalan Lor',
    'umkm.aboutDesc1': 'Desa Babalan Lor memiliki beragam UMKM yang bergerak di bidang konveksi, pangan olahan, dan usaha kreatif lainnya. UMKM menjadi tulang punggung perekonomian desa dengan menyerap banyak tenaga kerja lokal dan menggerakkan aktivitas ekonomi masyarakat.',
    'umkm.aboutDesc2': 'Produk yang dihasilkan UMKM Desa Babalan Lor telah dikenal kualitasnya dan dipasarkan ke berbagai daerah. Keberagaman jenis usaha menjadikan UMKM sebagai identitas ekonomi desa yang penting sekaligus peluang pengembangan di masa depan.',
    'umkm.daftar': 'Daftar UMKM',
    'umkm.daftarSub': 'Daftar UMKM di Desa Babalan Lor',
    'umkm.pemilik': 'Pemilik:',
    'umkm.alamat': 'Alamat:',
    'umkm.kontak': 'Kontak:',
    'umkm.berdiri': 'Berdiri:',
    'umkm.layanan': 'Layanan:',
    'umkm.visi': 'Visi',
    'umkm.visiDesc': 'Menjadi pusat industri konveksi jeans terdepan yang berkualitas tinggi dan berkelanjutan, meningkatkan kesejahteraan masyarakat Desa Babalan Lor.',
    'umkm.misi': 'Misi',
    'umkm.misi1': 'Meningkatkan kualitas produk jeans melalui inovasi dan teknologi',
    'umkm.misi2': 'Memberdayakan tenaga kerja lokal dengan pelatihan dan pengembangan keterampilan',
    'umkm.misi3': 'Memperluas pasar produk jeans ke berbagai daerah',
    'umkm.misi4': 'Menciptakan ekosistem bisnis yang berkelanjutan dan saling menguntungkan',
    'umkm.tableTitle': 'Tabel Profil UMKM',
    'umkm.tableSub': 'Data hasil survei usaha mikro, kecil, dan menengah di Desa Babalan Lor berdasarkan jenis usaha, pemilik, dan alamat.',
    'umkm.colNamaUsaha': 'Nama Usaha',
    'umkm.colNamaPemilik': 'Nama Pemilik',
    'umkm.colAlamatUsaha': 'Alamat Usaha',
    'umkm.colJenisProduk': 'Jenis Produk',
    'umkm.jenisTitle': 'Jenis dan Keberjalanan Usaha Desa Babalan Lor',
    'umkm.jenisSub': 'Ringkasan jenis usaha dan lama keberjalanan UMKM di Desa Babalan Lor berdasarkan hasil survei lapangan.',
    'umkm.jenisHeader': 'JENIS DAN KEBERJALANAN USAHA DESA BABALAN LOR',
    'umkm.colJenisUsaha': 'Jenis Usaha',
    'umkm.colJumlah': 'Jumlah',
    'umkm.colLamaKeberjalanan': 'Lama Keberjalanan',
    'umkm.financeTitle': 'Kondisi Keuangan UMKM',
    'umkm.financeSub': 'Ringkasan rata-rata pemasukan bulanan dan potensi pemasukan jika UMKM dioptimalkan.',
    'umkm.colRataPemasukan': 'Rata-rata Pemasukan (bulan)',
    'umkm.colPotensiPemasukan': 'Potensi Pemasukan (jika dioptimalkan)',
    // Project Page
    'project.hero': 'Project Maggot',
    'project.heroSub': 'Pengelolaan Sampah Organik dengan Teknologi Maggot',
    'project.about': 'Tentang Project',
    'project.aboutTitle': 'Project Maggot untuk Pengelolaan Sampah Organik',
    'project.aboutDesc1': 'Project Maggot adalah inisiatif inovatif untuk mengelola sampah organik di Desa Babalan Lor dengan memanfaatkan larva lalat hitam (Black Soldier Fly) atau yang dikenal sebagai maggot. Project ini bertujuan untuk mengurangi volume sampah organik sekaligus menghasilkan produk bernilai ekonomi tinggi.',
    'project.aboutDesc2': 'Melalui proses biokonversi, maggot mengonsumsi sampah organik dan mengubahnya menjadi produk yang bermanfaat. Maggot yang dihasilkan dapat dijual sebagai pakan ikan berkualitas tinggi, sementara limbah maggot (kasgot) dapat digunakan sebagai pupuk organik untuk tanaman.',
    'project.tujuan': 'Tujuan Project',
    'project.pengelolaan': 'Pengelolaan Sampah',
    'project.pengelolaanDesc': 'Mengurangi volume sampah organik di desa dengan cara yang ramah lingkungan dan berkelanjutan',
    'project.ekonomi': 'Ekonomi Berkelanjutan',
    'project.ekonomiDesc': 'Menciptakan sumber pendapatan baru melalui penjualan maggot sebagai pakan ikan dan kasgot sebagai pupuk',
    'project.pemberdayaan': 'Pemberdayaan Masyarakat',
    'project.pemberdayaanDesc': 'Memberikan peluang usaha dan peningkatan keterampilan masyarakat dalam pengelolaan sampah organik',
    'project.lele': 'Peternakan Lele',
    'project.leleTitle': 'Budidaya Ikan Lele untuk Peningkatan Ekonomi',
    'project.leleDesc1': 'Peternakan lele merupakan salah satu program pemberdayaan ekonomi masyarakat di Desa Babalan Lor. Budidaya ikan lele dipilih karena memiliki prospek yang baik, mudah dalam perawatan, dan memiliki nilai jual yang stabil di pasar. Program ini bertujuan untuk meningkatkan pendapatan masyarakat sekaligus memenuhi kebutuhan protein hewani lokal.',
    'project.leleDesc2': 'Ikan lele yang dibudidayakan menggunakan sistem kolam terpal atau kolam permanen dengan teknologi yang ramah lingkungan. Pakan yang digunakan dapat berasal dari maggot yang dihasilkan dari project maggot, menciptakan siklus ekonomi yang saling mendukung antara kedua program ini.',
    'project.produksi': 'Produksi Berkualitas',
    'project.produksiDesc': 'Ikan lele dibudidayakan dengan standar kualitas tinggi untuk memenuhi kebutuhan pasar lokal dan regional',
    'project.ekonomiLele': 'Ekonomi Berkelanjutan',
    'project.ekonomiLeleDesc': 'Menciptakan sumber pendapatan yang stabil dan berkelanjutan bagi peternak dan masyarakat desa',
    'project.pemberdayaanLele': 'Pemberdayaan Masyarakat',
    'project.pemberdayaanLeleDesc': 'Memberikan pelatihan dan pendampingan kepada masyarakat untuk mengembangkan usaha peternakan lele',
    'project.keunggulan': 'Keunggulan Budidaya Lele',
    'project.siklus': 'Siklus Panen Cepat',
    'project.siklusDesc': 'Ikan lele memiliki siklus panen yang relatif cepat, sekitar 2-3 bulan, sehingga memberikan return on investment yang baik bagi peternak.',
    'project.pasar': 'Pasar yang Stabil',
    'project.pasarDesc': 'Permintaan ikan lele di pasar lokal dan regional cenderung stabil sepanjang tahun, menjamin kontinuitas penjualan hasil panen.',
    'project.jenis': 'Jenis Maggot',
    'project.bsf': 'Black Soldier Fly (BSF)',
    'project.bsfDesc': 'Hermetia illucens adalah jenis lalat yang paling umum digunakan dalam budidaya maggot. Larva BSF memiliki kemampuan tinggi dalam mengonsumsi sampah organik dan mengubahnya menjadi biomassa berkualitas.',
    'project.efisien': 'Efisien dalam mengonsumsi sampah organik',
    'project.protein': 'Kandungan protein tinggi (40-45%)',
    'project.pakan': 'Cocok sebagai pakan ikan dan ternak',
    'project.siklusHidup': 'Siklus Hidup Black Soldier Fly',
    'project.siklusHidupDesc': 'Black Soldier Fly (BSF) memiliki siklus hidup yang terdiri dari 4 tahap utama: Telur, Larva (Maggot), Prepupa, dan Dewasa. Setiap tahap memiliki karakteristik dan peran penting dalam proses biokonversi sampah organik.',
    'project.telur': 'Telur',
    'project.telurDesc': 'Lalat betina dewasa bertelur di dekat sumber makanan. Telur berwarna putih krem, berukuran kecil (sekitar 1mm), dan menetas dalam 4-5 hari. Satu lalat betina dapat menghasilkan 500-900 telur.',
    'project.larva': 'Larva (Maggot)',
    'project.larvaDesc': 'Tahap paling produktif dalam siklus hidup. Larva mengalami 6 instar (tahap pertumbuhan) selama 14-18 hari. Pada tahap ini, maggot aktif mengonsumsi sampah organik dan tumbuh dari 1mm hingga mencapai panjang 2-3cm. Tahap ini menghasilkan produk utama: maggot dan kasgot.',
    'project.prepupa': 'Prepupa',
    'project.prepupaDesc': 'Setelah mencapai ukuran maksimal, larva berubah menjadi prepupa dengan warna hitam. Prepupa berhenti makan dan mencari tempat kering untuk bermetamorfosis. Tahap ini berlangsung 7-10 hari sebelum menjadi pupa.',
    'project.dewasa': 'Dewasa',
    'project.dewasaDesc': 'Lalat dewasa muncul dari pupa dan hidup selama 5-8 hari. Lalat dewasa tidak makan, hanya minum air, dan fokus pada reproduksi. Setelah kawin, lalat betina bertelur dan siklus dimulai kembali.',
    'project.karakteristik': 'Karakteristik Siklus Hidup',
    'project.durasi': 'Durasi Siklus:',
    'project.durasiValue': '35-45 hari dari telur hingga dewasa',
    'project.tahapProduktif': 'Tahap Produktif:',
    'project.tahapProduktifValue': 'Larva (14-18 hari) adalah tahap utama untuk produksi',
    'project.kondisi': 'Kondisi Optimal:',
    'project.kondisiValue': 'Suhu 25-30°C, kelembaban 60-70%',
    'project.produktivitas': 'Produktivitas:',
    'project.produktivitasValue': '1 kg sampah organik dapat menghasilkan 200-300g maggot',
    'project.produk': 'Produk yang Dihasilkan',
    'project.maggot': 'Maggot (Larva)',
    'project.maggotDesc': 'Maggot yang dihasilkan memiliki kandungan protein tinggi (40-45%) dan dapat dijual sebagai pakan ikan berkualitas. Maggot segar atau yang telah dikeringkan memiliki nilai ekonomi yang tinggi di pasar. Maggot juga kaya akan asam amino esensial, lemak, dan mineral yang dibutuhkan untuk pertumbuhan ikan dan ternak.',
    'project.nilaiEkonomi': 'Nilai Ekonomi Tinggi',
    'project.kasgot': 'Kasgot (Limbah Maggot)',
    'project.kasgotDesc': 'Kasgot adalah limbah yang dihasilkan setelah maggot mengonsumsi sampah organik. Kasgot kaya akan nutrisi (N, P, K) dan mikroorganisme menguntungkan, dapat digunakan sebagai pupuk organik yang sangat baik untuk tanaman. Kasgot memiliki pH netral dan struktur yang gembur, sehingga meningkatkan kesuburan tanah dan pertumbuhan tanaman.',
    'project.pupuk': 'Pupuk Organik Berkualitas',
    'project.proses': 'Proses Pengelolaan',
    'project.pengumpulan': 'Pengumpulan Sampah',
    'project.pengumpulanDesc': 'Sampah organik dikumpulkan dari rumah tangga',
    'project.budidaya': 'Budidaya Maggot',
    'project.budidayaDesc': 'Maggot dipelihara dan diberi makan sampah organik',
    'project.panen': 'Panen Maggot',
    'project.panenDesc': 'Maggot dipanen untuk dijual sebagai pakan ikan',
    'project.pemanfaatan': 'Pemanfaatan Kasgot',
    'project.pemanfaatanDesc': 'Kasgot digunakan sebagai pupuk organik',
    'project.panduanTitle': 'Buku Panduan Ternak Maggot',
    'project.panduanDesc': 'Buku panduan ini menjelaskan desain lengkap peternakan maggot Desa Babalan Lor, mulai dari tata letak bangunan, kandang, rak maggot, hingga mesin pengolah dan solar dryer sebagai solusi pengelolaan sampah organik.',
    // Profil KKN Page
    'kkn.hero': 'Profil KKN',
    'kkn.heroSub': 'Tim KKN Desa Babalan Lor - Project Maggot',
    'kkn.about': 'Tentang Tim KKN',
    'kkn.aboutDesc1': 'Tim Kuliah Kerja Nyata (KKN) Desa Babalan Lor terdiri dari 9 mahasiswa yang berdedikasi untuk memberikan kontribusi nyata kepada masyarakat desa. Melalui program KKN ini, kami berkomitmen untuk mengembangkan Desa Babalan Lor dengan fokus pada project maggot untuk pengelolaan sampah organik.',
    'kkn.aboutDesc2': 'Project maggot yang kami kembangkan bertujuan untuk mengatasi masalah sampah organik di desa sekaligus menciptakan peluang ekonomi baru. Melalui budidaya maggot, sampah organik dapat diubah menjadi produk bernilai tinggi seperti pakan ikan dan pupuk organik.',
    'kkn.anggota': 'Anggota Tim',
    'kkn.anggotaSub': '9 Anggota Tim KKN Desa Babalan Lor',
    'kkn.project': 'Project Maggot Kami',
    'kkn.projectTitle': 'Project Maggot untuk Pengelolaan Sampah',
    'kkn.projectDesc1': 'Sebagai bagian dari program KKN, kami mengembangkan project maggot yang bertujuan untuk mengelola sampah organik di Desa Babalan Lor. Project ini memanfaatkan larva lalat hitam (Black Soldier Fly) untuk mengubah sampah organik menjadi produk bernilai ekonomi tinggi.',
    'kkn.projectDesc2': 'Maggot yang dihasilkan dapat dijual sebagai pakan ikan berkualitas tinggi, sementara limbah maggot (kasgot) dapat digunakan sebagai pupuk organik untuk tanaman. Project ini tidak hanya membantu mengatasi masalah sampah, tetapi juga menciptakan peluang ekonomi baru bagi masyarakat desa.',
    'kkn.visi': 'Visi & Misi Tim',
    'kkn.visiTitle': 'Visi',
    'kkn.visiDesc': 'Menjadi tim KKN yang berkontribusi nyata dalam pengembangan Desa Babalan Lor melalui project maggot yang berkelanjutan dan memberikan manfaat jangka panjang bagi masyarakat.',
    'kkn.misiTitle': 'Misi',
    'kkn.misi1': 'Mengembangkan project maggot yang berkelanjutan',
    'kkn.misi2': 'Memberdayakan masyarakat dalam pengelolaan sampah organik',
    'kkn.misi3': 'Menciptakan peluang ekonomi baru bagi desa',
    'kkn.misi4': 'Meningkatkan kesadaran masyarakat tentang pentingnya pengelolaan sampah',
    'kkn.anggotaTim': 'Anggota Tim',
    'kkn.dedikasi': 'Dedikasi',
    // Common
    'common.lihatDetail': 'Lihat Detail',
    'common.pelajariLebih': 'Pelajari Lebih Lanjut',
    'common.kembali': 'Kembali',
  },
  en: {
    // Navigation
    'nav.beranda': 'Home',
    'nav.profilDesa': 'Village Profile',
    'nav.kampungTahu': 'Tofu Village',
    'nav.umkm': 'SME',
    'nav.project': 'Project',
    'nav.profilKkn': 'KKN Profile',
    // Hero
    'hero.title': 'Babalan Lor Village',
    'hero.subtitle': 'A village full of local production potential',
    'hero.explore': 'Explore Village',
    'hero.learnMore': 'Learn More',
    // About Section
    'about.title': 'About Babalan Lor Village',
    'about.desc1': 'Babalan Lor Village is a village located in an area rich in natural beauty and local culture. This village is known for its friendly community and strong spirit of mutual cooperation.',
    'about.desc2': 'With stunning scenery and cool air, Babalan Lor Village offers a harmonious living experience between humans and nature. The village community always maintains environmental sustainability while developing local potential for common welfare.',
    'about.quote': 'Together building a prosperous and sustainable village',
    // Filosofi
    'filosofi.title': 'Village Philosophy',
    'filosofi.quote': 'Realizing an independent, cultured, and prosperous village by upholding local wisdom values.',
    'filosofi.desc': 'The philosophy of Babalan Lor Village emphasizes the principles of independence, cultural preservation, and community welfare. We believe that by maintaining and developing the local wisdom that has been passed down from generation to generation, the village can grow into a strong, harmonious, and sustainable community.',
    // Stats
    'stats.title': 'Village Data',
    'stats.subtitle': 'Statistics and general information about Babalan Lor Village',
    'stats.penduduk': 'Population',
    'stats.rw': 'RW',
    'stats.rt': 'RT',
    'stats.keluarga': 'Families',
    // Features
    'features.title': 'Village Advantages',
    'features.subtitle': 'Things that make Babalan Lor Village special',
    'features.alam': 'Natural Beauty',
    'features.alamDesc': 'A village with stunning scenery and cool air, surrounded by green rice fields.',
    'features.budaya': 'Local Culture',
    'features.budayaDesc': 'Well-preserved local wisdom, including traditions and customs passed down from generation to generation.',
    'features.gotong': 'Mutual Cooperation',
    'features.gotongDesc': 'The spirit of mutual cooperation is still very strong in daily community life.',
    'features.ekonomi': 'Economic Potential',
    'features.ekonomiDesc': 'Various local economic potentials that continue to be developed to improve community welfare.',
    // Map
    'map.title': 'Village Location',
    'map.subtitle': 'Find the location of Babalan Lor Village on the map',
    'map.address': 'Address:',
    'map.addressValue': 'Babalan Lor Village, Bojong District, Pekalongan Regency, Central Java',
    'map.directions': 'Get Directions',
    // Footer
    'footer.mission': 'Realizing an independent, cultured, and prosperous village by upholding local wisdom values.',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact Us',
    'footer.copyright': '© 2026 Babalan Lor Village Government. All rights reserved.',
    // Profil Desa Page
    'profilDesa.hero': 'Village Profile',
    'profilDesa.heroSub': 'Complete information about Babalan Lor Village',
    'profilDesa.lokasi': 'Geographic Location',
    'profilDesa.koordinat': 'Geographic Coordinates',
    'profilDesa.kecamatan': 'District:',
    'profilDesa.kabupaten': 'Regency:',
    'profilDesa.ketinggian': 'Elevation:',
    'profilDesa.ketinggianValue': '± 50 meters above sea level',
    'profilDesa.batas': 'Territorial Boundaries',
    'profilDesa.utara': 'North:',
    'profilDesa.selatan': 'South:',
    'profilDesa.timur': 'East:',
    'profilDesa.barat': 'West:',
    'profilDesa.data': 'Geographic Data',
    'profilDesa.jumlahPenduduk': 'Total Population',
    'profilDesa.jumlahKeluarga': 'Total Families',
    'profilDesa.luasWilayah': 'Area Size',
    'profilDesa.struktur': 'Village Government Structure',
    'profilDesa.usaha': 'Local Business',
    'profilDesa.jeanConvection': 'Jean Convection',
    'profilDesa.industri': 'Jeans Convection Industry',
    'profilDesa.industriDesc1': 'Babalan Lor Village is known as a rapidly developing center of jeans convection industry. The jeans convection business has become the backbone of the village economy, absorbing many local workers and making a significant contribution to community welfare.',
    'profilDesa.industriDesc2': 'Jeans products produced by local entrepreneurs in Babalan Lor Village have been recognized for their quality and marketed to various regions. This industry not only provides employment, but also becomes a proud economic identity of the village.',
    'profilDesa.unitUsaha': 'Business Units',
    'profilDesa.tenagaKerja': 'Workers',
    'profilDesa.lihatUMKM': 'View UMKM Details',
    // Kampung Tahu Page
    'kampungTahu.hero': 'Tofu Village',
    'kampungTahu.heroSub': 'Innovative Educational Tourism in Babalan Lor Village',
    'kampungTahu.about': 'About Tofu Village',
    'kampungTahu.aboutDesc1': 'Tofu Village in Babalan Lor Village is a unique educational tourism destination, offering direct experience in the traditional tofu making process. Visitors can learn about local wisdom and the tofu production process that has become part of village community life.',
    'kampungTahu.aboutDesc2': 'Through collaboration with various parties, Tofu Village continues to be developed as an innovative educational tourism center, combining local traditions with modern tourism concepts to improve community welfare.',
    'kampungTahu.wisata': 'Educational Tourism',
    'kampungTahu.wisataDesc': 'Learn the traditional tofu making process directly from experienced craftsmen',
    'kampungTahu.kearifan': 'Local Wisdom',
    'kampungTahu.kearifanDesc': 'Experience the preserved local wisdom that is part of daily life',
    'kampungTahu.ekonomi': 'Local Economy',
    'kampungTahu.ekonomiDesc': 'Support the local economy by buying tofu products directly from craftsmen',
    'kampungTahu.proses': 'Tofu Making Process',
    'kampungTahu.persiapan': 'Preparation',
    'kampungTahu.persiapanDesc': 'Prepare quality soybean raw materials',
    'kampungTahu.pengolahan': 'Processing',
    'kampungTahu.pengolahanDesc': 'Soaking and grinding process',
    'kampungTahu.pembentukan': 'Forming',
    'kampungTahu.pembentukanDesc': 'Forming tofu with traditional molds',
    'kampungTahu.pemasakan': 'Cooking',
    'kampungTahu.pemasakanDesc': 'Cooking and packaging process',
    // UMKM Page
    'umkm.hero': 'SME',
    'umkm.heroSub': 'Micro, Small and Medium Enterprises in Babalan Lor Village',
    'umkm.about': 'About SMEs in Babalan Lor Village',
    'umkm.aboutDesc1': 'Babalan Lor Village has various SMEs operating in garment, food processing, and other creative sectors. These SMEs form the backbone of the village economy, absorbing many local workers and driving community economic activity.',
    'umkm.aboutDesc2': 'Products produced by SMEs in Babalan Lor Village are recognized for their quality and are marketed to various regions. The diversity of business types makes SMEs an important economic identity of the village and a promising development opportunity for the future.',
    'umkm.daftar': 'SME List',
    'umkm.daftarSub': 'List of SMEs in Babalan Lor Village',
    'umkm.pemilik': 'Owner:',
    'umkm.alamat': 'Address:',
    'umkm.kontak': 'Contact:',
    'umkm.berdiri': 'Established:',
    'umkm.layanan': 'Services:',
    'umkm.visi': 'Vision',
    'umkm.visiDesc': 'To become a leading, high-quality and sustainable jeans convection industry center, improving the welfare of Babalan Lor Village community.',
    'umkm.misi': 'Mission',
    'umkm.misi1': 'Improve jeans product quality through innovation and technology',
    'umkm.misi2': 'Empower local workers with training and skill development',
    'umkm.misi3': 'Expand jeans product market to various regions',
    'umkm.misi4': 'Create a sustainable and mutually beneficial business ecosystem',
    'umkm.tableTitle': 'SME Profile Table',
    'umkm.tableSub': 'Survey data of micro, small, and medium enterprises in Babalan Lor Village including business name, owner, address, and product types.',
    'umkm.colNamaUsaha': 'Business Name',
    'umkm.colNamaPemilik': 'Owner',
    'umkm.colAlamatUsaha': 'Business Address',
    'umkm.colJenisProduk': 'Product Type',
    'umkm.jenisTitle': 'Business Types and Duration in Babalan Lor Village',
    'umkm.jenisSub': 'Summary of SME business types and years in operation based on field survey data.',
    'umkm.jenisHeader': 'TYPES AND BUSINESS DURATION OF SMEs IN BABALAN LOR VILLAGE',
    'umkm.colJenisUsaha': 'Business Type',
    'umkm.colJumlah': 'Total',
    'umkm.colLamaKeberjalanan': 'Years in Operation',
    'umkm.financeTitle': 'SME Financial Overview',
    'umkm.financeSub': 'Summary of average monthly income and potential income if SMEs are fully optimized.',
    'umkm.colRataPemasukan': 'Average Income (monthly)',
    'umkm.colPotensiPemasukan': 'Potential Income (if optimized)',
    // Project Page
    'project.hero': 'Maggot Project',
    'project.heroSub': 'Organic Waste Management with Maggot Technology',
    'project.about': 'About Project',
    'project.aboutTitle': 'Maggot Project for Organic Waste Management',
    'project.aboutDesc1': 'Maggot Project is an innovative initiative to manage organic waste in Babalan Lor Village by utilizing black soldier fly larvae (Black Soldier Fly) or known as maggot. This project aims to reduce organic waste volume while producing high economic value products.',
    'project.aboutDesc2': 'Through the bioconversion process, maggots consume organic waste and convert it into useful products. The maggots produced can be sold as high-quality fish feed, while maggot waste (kasgot) can be used as organic fertilizer for plants.',
    'project.tujuan': 'Project Goals',
    'project.pengelolaan': 'Waste Management',
    'project.pengelolaanDesc': 'Reduce organic waste volume in the village in an environmentally friendly and sustainable way',
    'project.ekonomi': 'Sustainable Economy',
    'project.ekonomiDesc': 'Create new sources of income through the sale of maggots as fish feed and kasgot as fertilizer',
    'project.pemberdayaan': 'Community Empowerment',
    'project.pemberdayaanDesc': 'Provide business opportunities and improve community skills in organic waste management',
    'project.lele': 'Catfish Farming',
    'project.leleTitle': 'Catfish Farming for Economic Improvement',
    'project.leleDesc1': 'Catfish farming is one of the community economic empowerment programs in Babalan Lor Village. Catfish farming was chosen because it has good prospects, is easy to maintain, and has stable market value. This program aims to increase community income while meeting local animal protein needs.',
    'project.leleDesc2': 'Catfish are cultivated using tarpaulin pond or permanent pond systems with environmentally friendly technology. The feed used can come from maggots produced from the maggot project, creating an economically supportive cycle between these two programs.',
    'project.produksi': 'Quality Production',
    'project.produksiDesc': 'Catfish are cultivated with high quality standards to meet local and regional market needs',
    'project.ekonomiLele': 'Sustainable Economy',
    'project.ekonomiLeleDesc': 'Create stable and sustainable sources of income for farmers and village communities',
    'project.pemberdayaanLele': 'Community Empowerment',
    'project.pemberdayaanLeleDesc': 'Provide training and mentoring to the community to develop catfish farming businesses',
    'project.keunggulan': 'Catfish Farming Advantages',
    'project.siklus': 'Fast Harvest Cycle',
    'project.siklusDesc': 'Catfish have a relatively fast harvest cycle, around 2-3 months, providing good return on investment for farmers.',
    'project.pasar': 'Stable Market',
    'project.pasarDesc': 'Demand for catfish in local and regional markets tends to be stable throughout the year, ensuring continuity of harvest sales.',
    'project.jenis': 'Maggot Types',
    'project.bsf': 'Black Soldier Fly (BSF)',
    'project.bsfDesc': 'Hermetia illucens is the most commonly used fly species in maggot cultivation. BSF larvae have high ability to consume organic waste and convert it into quality biomass.',
    'project.efisien': 'Efficient in consuming organic waste',
    'project.protein': 'High protein content (40-45%)',
    'project.pakan': 'Suitable as fish and livestock feed',
    'project.siklusHidup': 'Black Soldier Fly Life Cycle',
    'project.siklusHidupDesc': 'Black Soldier Fly (BSF) has a life cycle consisting of 4 main stages: Egg, Larva (Maggot), Prepupa, and Adult. Each stage has characteristics and important roles in the organic waste bioconversion process.',
    'project.telur': 'Egg',
    'project.telurDesc': 'Adult female flies lay eggs near food sources. Eggs are creamy white, small in size (about 1mm), and hatch in 4-5 days. One female fly can produce 500-900 eggs.',
    'project.larva': 'Larva (Maggot)',
    'project.larvaDesc': 'The most productive stage in the life cycle. Larvae go through 6 instars (growth stages) over 14-18 days. At this stage, maggots actively consume organic waste and grow from 1mm to reach 2-3cm in length. This stage produces the main products: maggots and kasgot.',
    'project.prepupa': 'Prepupa',
    'project.prepupaDesc': 'After reaching maximum size, larvae turn into prepupa with black color. Prepupa stop eating and seek dry places to metamorphose. This stage lasts 7-10 days before becoming pupa.',
    'project.dewasa': 'Adult',
    'project.dewasaDesc': 'Adult flies emerge from pupa and live for 5-8 days. Adult flies do not eat, only drink water, and focus on reproduction. After mating, female flies lay eggs and the cycle begins again.',
    'project.karakteristik': 'Life Cycle Characteristics',
    'project.durasi': 'Cycle Duration:',
    'project.durasiValue': '35-45 days from egg to adult',
    'project.tahapProduktif': 'Productive Stage:',
    'project.tahapProduktifValue': 'Larva (14-18 days) is the main stage for production',
    'project.kondisi': 'Optimal Conditions:',
    'project.kondisiValue': 'Temperature 25-30°C, humidity 60-70%',
    'project.produktivitas': 'Productivity:',
    'project.produktivitasValue': '1 kg of organic waste can produce 200-300g of maggots',
    'project.produk': 'Products Produced',
    'project.maggot': 'Maggot (Larva)',
    'project.maggotDesc': 'The maggots produced have high protein content (40-45%) and can be sold as quality fish feed. Fresh or dried maggots have high economic value in the market. Maggots are also rich in essential amino acids, fats, and minerals needed for fish and livestock growth.',
    'project.nilaiEkonomi': 'High Economic Value',
    'project.kasgot': 'Kasgot (Maggot Waste)',
    'project.kasgotDesc': 'Kasgot is waste produced after maggots consume organic waste. Kasgot is rich in nutrients (N, P, K) and beneficial microorganisms, can be used as excellent organic fertilizer for plants. Kasgot has neutral pH and loose structure, thus improving soil fertility and plant growth.',
    'project.pupuk': 'Quality Organic Fertilizer',
    'project.proses': 'Management Process',
    'project.pengumpulan': 'Waste Collection',
    'project.pengumpulanDesc': 'Organic waste is collected from households',
    'project.budidaya': 'Maggot Cultivation',
    'project.budidayaDesc': 'Maggots are raised and fed organic waste',
    'project.panen': 'Maggot Harvest',
    'project.panenDesc': 'Maggots are harvested to be sold as fish feed',
    'project.pemanfaatan': 'Kasgot Utilization',
    'project.pemanfaatanDesc': 'Kasgot is used as organic fertilizer',
    'project.panduanTitle': 'Maggot Farming Guidebook',
    'project.panduanDesc': 'This guidebook explains the complete design of the maggot farm in Babalan Lor Village, from building layout and cages to maggot racks, processing machines, and solar dryer as a solution for organic waste management.',
    // Profil KKN Page
    'kkn.hero': 'KKN Profile',
    'kkn.heroSub': 'Babalan Lor Village KKN Team - Maggot Project',
    'kkn.about': 'About KKN Team',
    'kkn.aboutDesc1': 'The Community Service Program (KKN) team of Babalan Lor Village consists of 9 dedicated students committed to making real contributions to the village community. Through this KKN program, we are committed to developing Babalan Lor Village with a focus on the maggot project for organic waste management.',
    'kkn.aboutDesc2': 'The maggot project we are developing aims to address organic waste problems in the village while creating new economic opportunities. Through maggot cultivation, organic waste can be converted into high-value products such as fish feed and organic fertilizer.',
    'kkn.anggota': 'Team Members',
    'kkn.anggotaSub': '9 Babalan Lor Village KKN Team Members',
    'kkn.project': 'Our Maggot Project',
    'kkn.projectTitle': 'Maggot Project for Waste Management',
    'kkn.projectDesc1': 'As part of the KKN program, we are developing a maggot project aimed at managing organic waste in Babalan Lor Village. This project utilizes black soldier fly larvae (Black Soldier Fly) to convert organic waste into high economic value products.',
    'kkn.projectDesc2': 'The maggots produced can be sold as high-quality fish feed, while maggot waste (kasgot) can be used as organic fertilizer for plants. This project not only helps address waste problems, but also creates new economic opportunities for the village community.',
    'kkn.visi': 'Team Vision & Mission',
    'kkn.visiTitle': 'Vision',
    'kkn.visiDesc': 'To become a KKN team that makes real contributions to the development of Babalan Lor Village through a sustainable maggot project that provides long-term benefits to the community.',
    'kkn.misiTitle': 'Mission',
    'kkn.misi1': 'Develop a sustainable maggot project',
    'kkn.misi2': 'Empower the community in organic waste management',
    'kkn.misi3': 'Create new economic opportunities for the village',
    'kkn.misi4': 'Increase community awareness about the importance of waste management',
    'kkn.anggotaTim': 'Team Members',
    'kkn.dedikasi': 'Dedication',
    // Common
    'common.lihatDetail': 'View Details',
    'common.pelajariLebih': 'Learn More',
    'common.kembali': 'Back',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('id')

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language
    if (saved && (saved === 'id' || saved === 'en')) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
